name: Submission
on:
  pull_request:
    types: [labeled]
jobs:
  submit:
    name: Submit
    if: ${{ github.event.label.name == 'Submitted' }}
    runs-on: maven:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: cd ./flight-service && mvn clean install

